apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-stable.yaml
  - service-canary.yaml
  - secrets.yaml
  - configmap.yaml
  - ingress.yaml
  - rollout.yaml
  - p99-latency.yaml
  - success-rate.yaml