---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      vus: 4,
      duration: '1300s',
    };
    export default function() {
      const res = http.get('http://rollouts-poc.vidp-mgmt-00-test-euc1.test0.shared.vidp.dev.euc1.vonagenetworks.net/color');
      check(res, {
        'status was 200': (r) => r.status === 200,
        'response time OK': (r) => r.timings.duration < 200,
      });
      sleep(1);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-http-benchmark
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        args: ["run", "/scripts/script.js"]
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: k6-script
        configMap:
          name: k6-test-script
      tolerations:
        - effect: NoSchedule
          key: vidp
          value: "true"
      restartPolicy: OnFailure
  backoffLimit: 1
---
